### ISSUE TITLE
has_object_read_permission returning False Still Allows Read

### ISSUE THREAD

**Issue by jessemorton** [Helioscene/dry-rest-permissions#4]
I'm having trouble making use of `has_object_read_permission` - perhaps I'm doing it wrong? Here's what I've got:

```
    @staticmethod
    @authenticated_users
    def has_write_permission(request):
        return True

    @staticmethod
    def has_read_permission(request):
        # this seems to counter-act the has_object_read_permission down below,
        # but if I take out has_read_permission, then DRY Rest Permissions throws an assertion error
        return True

    def has_object_write_permission(self, request):
        return request.user.accounts.filter(id=self.account.id).exists()

    def has_object_read_permission(self, request):
        return request.user.accounts.filter(id=self.account.id).exists()
```

My goal is this: for a given object X that is owned by account Y, only let users that are part of account Y to read the object. With the code above, I'm still able to read object X, even though part of object X's output is:

```
    "permissions": {
        "write": false,
        "read": false
    }
```

I've confirmed that the user I'm testing with is not staff/superuser.

**Comment by dbkaplan** [comment]
Hi Jesse,

Can you also post a snippet of what your view looks like. 
I am wondering if you are using DRYGlobalPermissions in your permissions rather than DRYPermissions. The difference is that DRYPermissions will look at both global (e.g. has_read_permission) and object permissions (e.g. has_object_read_permission), while DRYGlobalPermissions will only look at global permissions.

Also can you stick a 'print "here"' statement inside of your has_object_read_permissions function before the return to make sure it is being called.

**Comment by dbkaplan** [comment]
Another quick couple of notes.

The reason you need the has_read_permission is because global permissions are always called first before object permissions. If they fail then permissions are returned False. However, if they succeed then the object level permissions are then called. Think of it like this: First you check whether the user has access to the whole table, then you check whether they have access to the row.

If your global permissions are always true...then you can use DRYObjectPermissions on your view, which will always assume true for global permissions and skip those checks.

**Comment by jessemorton** [comment]
Thanks for the speedy response. You pointed me in the right direction: in my view, I'm overwriting the `create` action, so per http://www.django-rest-framework.org/api-guide/permissions/#object-level-permissions I need to manually do `self.check_object_permissions(self.request, object)` since it won't be done automatically for me.

Thanks for the framework! Looks thought through and very useful.

**Comment by dbkaplan** [comment]
Glad to help!
